# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
np.show_config()

2.4.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [14]:
zero.size * zero.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [2]:
m = np.arange(0,9)
m = m.reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
np.random.rand(3,3,3)

array([[[0.9473811 , 0.60285902, 0.04020389],
        [0.47728969, 0.79813721, 0.97046408],
        [0.59778498, 0.43844657, 0.08197688]],

       [[0.91165364, 0.7239041 , 0.2460315 ],
        [0.03597454, 0.61770593, 0.1193372 ],
        [0.89097726, 0.32200751, 0.08684475]],

       [[0.02962089, 0.9652254 , 0.70985454],
        [0.16799184, 0.749553  , 0.60688807],
        [0.82904397, 0.01399276, 0.49463589]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [8]:
r = np.random.rand(10,10)

np.max(r), np.min(r)

(np.float64(0.9986983387582096), np.float64(0.004550696614186611))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
r2 = np.random.rand(30)
np.mean(r2)

np.float64(0.5864744781847995)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
o = np.ones((5,5))

o[1:-1, 1:-1] = 0

o


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))

np.pad(a, pad_width=1, mode="constant", constant_values=0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [30]:
a = np.zeros((8,8))

a[::2, ::2] = 1
a[1::2, 1::2] = 1

a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [42]:
r = np.random.rand(5,5)
m = np.mean(r)
r = (r-m) / (np.std(r))
r

array([[ 0.26200822,  1.36205207, -0.55654531, -1.28123444,  1.41517232],
       [-0.73755757,  0.1043913 , -0.43617618, -0.33630999, -0.33054495],
       [-1.13479277, -0.78231039,  1.44379611,  1.58712839, -0.4801348 ],
       [-0.57638896,  1.37221512,  0.00512006,  0.70921337, -1.46345406],
       [ 1.44599967,  1.12955532, -0.67804627, -0.45275402, -1.59040225]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [43]:
color = np.dtype([("r", np.ubyte),("b", np.ubyte), ("g", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [45]:
A = np.random.rand(5,3)
B = np.random.rand(3,2)

A @ B

array([[0.18879623, 0.31756134],
       [0.8687779 , 1.33369802],
       [0.67106722, 1.06627186],
       [0.52738909, 1.0609721 ],
       [0.65812962, 0.56174761]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [50]:
Z = np.arange(11)
Z[(3<Z) & (Z<8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

# For Python built-in `sum`, the second argument is `start value`.
# For NumPY `sum`, the second argument is `axis`. `-1` means the last axis.

range(0, 5)
range(0, 5)


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Element-wise

Z**Z
2<<Z>>2
Z<-Z # comparison
1j*Z # Complex Numbers
Z/1/1

# In Numpy, the complex unit is `j`

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [58]:
a1 = np.array(0) / np.array(0)
b1 = np.array(0) // np.array(0)
c1 = np.array([np.nan]).astype(int).astype(float)
print(a1,b1,c1)

nan 0 [0.]


/var/folders/27/wcnmtw7976b53f6nng6wp3zm0000gn/T/ipykernel_38525/1212068331.py:1: RuntimeWarning: invalid value encountered in divide
  a1 = np.array(0) / np.array(0)
/var/folders/27/wcnmtw7976b53f6nng6wp3zm0000gn/T/ipykernel_38525/1212068331.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  b1 = np.array(0) // np.array(0)
/var/folders/27/wcnmtw7976b53f6nng6wp3zm0000gn/T/ipykernel_38525/1212068331.py:3: RuntimeWarning: invalid value encountered in cast
  c1 = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# Alt
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[  7.  -6.   3.   4.  -5.  10.  -5. -10.  -1.  -7.]
[  7.  -6.   3.   4.  -5.  10.  -5. -10.  -1.  -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [80]:
Z1 = np.random.randint(0, 200, 100)
Z2 = np.random.randint(0, 200, 100)

np.intersect1d(Z1, Z2)

array([ 12,  30,  31,  33,  35,  41,  57,  62,  64,  68,  91,  95, 105,
       106, 110, 112, 120, 140, 143, 150, 153, 154, 155, 166, 167, 181,
       184, 193, 196])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [70]:
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

# emath gets imaginary numbers

/var/folders/27/wcnmtw7976b53f6nng6wp3zm0000gn/T/ipykernel_38525/1467658155.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

print(yesterday, today, tomorrow)

2026-02-22 2026-02-23 2026-02-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [11]:
# To calculate in-place, ufuncs must be used with the out parameter.
# Otherwise, numpy creates temporary arrays for the calculation.

A = np.ones((5,5))
B = np.ones((5,5))

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.multiply(A,-1,out=A)
np.divide(B,A,out=A)

print(A)

[[-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]
 [-4. -4. -4. -4. -4.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0, 10, 10)

print(Z - Z%1) # Modulo: Z%1 gets the decimal part
print(Z // 1) 
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z)) # Rounding towards zero

[2. 3. 2. 1. 1. 5. 6. 1. 1. 8.]
[2. 3. 2. 1. 1. 5. 6. 1. 1. 8.]
[2. 3. 2. 1. 1. 5. 6. 1. 1. 8.]
[2 3 2 1 1 5 6 1 1 8]
[2. 3. 2. 1. 1. 5. 6. 1. 1. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
Z = np.zeros((5,5))
Z += np.arange(5)

print(Z)

# Alt

Z = np.tile(np.arange(5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [18]:
def gen():
    for x in range(10):
        yield x
        
Z = np.fromiter(gen(), dtype=float, count=-1) 
print(Z)

# -1 means until exhaustion

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [19]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [21]:
Z = np.random.uniform(0,100,10)
Z.sort()
print(Z)

[ 7.77308334 22.63973046 32.50556706 36.9704951  38.82344893 46.99722385
 53.26293598 71.68672315 88.84191835 98.53628907]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.random.uniform(0, 10 ,1000)
np.add.reduce(Z)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.uniform(0,10, 10)
B = np.random.uniform(0,10, 10)

np.allclose(A,B) # Handles FP well

np.array_equal(A,B) # EXACT Equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [7]:
A = np.zeros(10)
A.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [8]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.78233444 0.78008839 0.97712543 0.62346018 0.69172399 0.5830774
 0.44112997 0.09744196 0.71670985 0.94916456]
[1.5092117  0.31808879 1.46130099 1.15481084 0.60933197 0.63899035
 0.09325022 1.02007792 1.4762621  0.4074462 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [13]:
Z = np.random.randint(1,100,10)
Z[np.argmax(Z)] = 0
print(Z)

[14 37 27 90 16 63 93 48  0 59]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [17]:
Z = np.zeros((5,5), dtype=[('x', np.float32), ('y', np.float32)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [18]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y) # Try every combination

print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [19]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [20]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [23]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [6]:
coord = np.dtype([("x", np.float64), ("y", np.float64)])
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte)])

Z = np.zeros(10, dtype=np.dtype([("coord", coord), ("color", color)]))

print(Z)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [14]:
Z = np.random.random((10,2))

# convert input to arrays with at least 2d
X,Y = np.atleast_2d(Z[:,0], Z[:,1])

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)

[[0.         0.84770463 0.84469118 0.47798021 0.78164887 0.94938934
  0.51520339 0.57049531 0.81910622 0.66988803]
 [0.84770463 0.         0.08665605 0.66331714 0.23841929 0.58715363
  0.48471528 0.69426209 0.56234698 0.39858647]
 [0.84469118 0.08665605 0.         0.70973093 0.15907092 0.500803
  0.53120321 0.6337685  0.48041667 0.33078467]
 [0.47798021 0.66331714 0.70973093 0.         0.74350092 1.05445775
  0.17890989 0.8377507  0.95304781 0.74239174]
 [0.78164887 0.23841929 0.15907092 0.74350092 0.         0.36153749
  0.57312163 0.48627333 0.32408331 0.18013699]
 [0.94938934 0.58715363 0.500803   1.05445775 0.36153749 0.
  0.89953036 0.43607069 0.1331413  0.31354503]
 [0.51520339 0.48471528 0.53120321 0.17890989 0.57312163 0.89953036
  0.         0.73756284 0.80772274 0.59315824]
 [0.57049531 0.69426209 0.6337685  0.8377507  0.48627333 0.43607069
  0.73756284 0.         0.30660472 0.30614225]
 [0.81910622 0.56234698 0.48041667 0.95304781 0.32408331 0.1331413
  0.80772274 0.30660472

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
# Create a new array 'Y' that shares the exact same memory buffer as 'Z'.
# However, 'Y' is instructed to interpret that binary data as 32-bit integers.
# (This is only possible because float32 and int32 both occupy 4 bytes).
# Binary Reinterpretation
Y = Z.view(np.int32)
# Copy the values from 'Z' into 'Y'.
# Y = Z but different interpretation (dtype)
# Converting in place
Y[:] = Z
print(Y)

[48 64 37 22 93 96 15 60 22 87]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype = int, filling_values = 0)
print(Z)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [17]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)